### ISSUE TITLE
It would be even better if bridging could be supported

### ISSUE THREAD

**Issue by zuohuadong** [iranee/qnap-zerotier#1]
Try:

![image](https://github.com/iranee/qnap-zerotier/assets/11203929/a0d4c217-c7eb-4835-a67d-a68d02343d41)

![image](https://github.com/iranee/qnap-zerotier/assets/11203929/5ac8ec56-41dc-44c8-adba-02f9f2666ecb)

see：
https://docs.zerotier.com/bridging

**Comment by iranee** [comment]
Thank you for the suggestion. We plan to support bridging in the next release.

**Comment by iranee** [comment]
Thank you for the suggestion. I need to configure it first. If successful, bridging functionality could be included in the next release.

**Comment by iranee** [comment]
Bridging is now supported.
