### ISSUE TITLE
zerotier-idtool 找不到~~~

### ISSUE THREAD

**Issue by LeonLyon** [iranee/qnap-zerotier#3]
您好。
我试图在我的QNAP上面建立Moon节点中转服务器，会需要用到zerotier-idtool命令。安装后我试图使用该命令，但系统提示zerotier-idtool命令不存在。
请问是怎么回事？我该怎么修复呢？
谢谢。

**Comment by iranee** [comment]
可以使用命令 $QPKG_ROOT/zerotier-one -i 来配置
